run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gocyclo
    - gofumpt
    - misspell
    - revive
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0
